version: '3.4'

services:
  operationservice:
    image: ${DOCKER_REGISTRY-}operationservice
    build:
      context: .
      dockerfile: OperationService/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      bank-network:
    depends_on:
      - sqlserverdocker
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      bank-network:
    depends_on:
      - sqlserverdocker
  sqlserverdocker:
    container_name: sql-server-docker
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "8100:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPassword*1234
    networks:
      - bank-network

networks:
  bank-network: