version: '3.4'

services:
  operationservice:
    image: ${DOCKER_REGISTRY-}operationservice
    build:
      context: .
      dockerfile: OperationService/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - sql-server
    networks:
      - bank_network
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql-server
    networks:
      - bank_network
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=P@assword4Secret!
      - ACCEPT_EULA=Y
    volumes:
      - ./docker/volumes/azure-sql-edge/data:/var/opt/mssql/data
      - ./docker/volumes/azure-sql-edge/log:/var/opt/mssql/log
      - ./docker/volumes/azure-sql-edge/secrets:/var/opt/mssql/secrets
    networks:
      - bank_network


# volumes:
#   operations-data:
#   user-data:
#   sql-data:

networks:
  bank_network:
    name: bank_network
    driver: bridge

